[package]
name = "pancake"
version = "0.1.0"
edition = "2021"
description="Geometry processing library"
license="MIT"
homepage = "https://github.com/dima634/pancake"
repository = "https://github.com/dima634/pancake"
keywords = ["mesh", "mesh-processing", "geometry", "computational-geometry", "algorithms"]
categories = ["mathematics", "graphics", "data-structures"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.31.2"
nalgebra-glm = "0.17.0"
simba = "0.7.2"
num-traits = "0.2.15"
bitflags = "1.3.2"
tabled = "0.10.0"
petgraph = "0.6.2"
