[package]
name = "pancake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.31.1"
nalgebra-glm = "0.17.0"
simba = "0.7.2"
num-traits = "0.2.15"
bitflags = "1.3.2"
tabled = "0.8.0"
wasm-bindgen = "0.2.82"
petgraph = "0.6.2"
