[package]
name = "baby_shark"
version = "0.1.1"
edition = "2021"
description="Geometry processing library"
license="MIT"
homepage = "https://github.com/dima634/baby_shark"
repository = "https://github.com/dima634/baby_shark"
keywords = ["mesh", "mesh-processing", "geometry", "computational-geom", "algorithms"]
categories = ["mathematics", "graphics", "data-structures"]
exclude = [
    ".github/workflows/*",
    ".vscode/*"
]

[dependencies]
nalgebra = "0.31.2"
nalgebra-glm = "0.17.0"
simba = "0.7.2"
num-traits = "0.2.15"
bitflags = "1.3.2"
tabled = "0.10.0"
petgraph = "0.6.2"

[dev-dependencies]
test-case = "3.0.0"